apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abhi702/backend:13
        ports:
        - containerPort: 5000
        env:
        # Load from Secret (Sensitive Data)
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
              
        # Load from ConfigMap (Non-Sensitive Data)
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
      
        - name: JWT_EXPIRY
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_EXPIRY

        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_SECRET

        - name: CORS_ORIGIN
          value: "http://frontend-service:80"      
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32694  # Ensure it's accessible externally

